name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
      run: make < tests/input
      
    - name: Test1
      run: make < tests/test1

    - name: Test2
      run: make < tests/test2

    - name: Test3
      run: make < tests/test3

    - name: Test4
      run: make < tests/test4