name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
      run: make < tests/input
      
    - name: Test1
      run: make < tests/test1

    - name: Test2
      run: make < tests/test2

    - name: Test3
      run: make < tests/test3

    - name: Test4
      run: make < tests/test4

    - name: InvalidTest1 (Incorrect amount of tests)
      run: make < tests/invalidTest1
    
    - name: InvalidTest2 (Missing white dot on line)
      run: make < tests/invalidTest2
      
    - name: InvalidTest3 (Incorrect map width)
      run: make < tests/invalidTest3

    - name: InvalidTest4 (Incorrect map height)
      run: make < tests/invalidTest4
      
    - name: InvalidTest5 (Invalid map Width)
      run: make < tests/invalidTest5

    - name: InvalidTest6 (Invalid map height)
      run: make < tests/invalidTest6

    - name: InvalidTest7 (Invalid amount of tests)
      run: make < tests/invalidTest7
      